### ISSUE TITLE
Allow for some clockskew

### ISSUE THREAD

**Issue by danpfe** [kumuluz/kumuluzee-jwt-auth#10]
Hi guys,

please accept my PR at https://github.com/kumuluz/kumuluzee-jwt-auth/pull/9.

Found out that the default allowed clockskew is exactly 0, so not very much ;) In some cases it's probably good to allow some wiggle-room.

Updated the code and the README-file explaining how to adjust the maximum leeway.

/Daniel

**Comment by osbeorn** [comment]
Seems alright to me. Thanks for the contribution.
