### ISSUE TITLE
Security issue - JWTAuthorizationFilter accept requests without authorization header

### ISSUE THREAD

**Issue by ribicnejc** [kumuluz/kumuluzee-jwt-auth#12]
JWTAuthorizationFilter does not reject request if request doesn't contain any authorization header.
In other words - this security issue allows every request to the resource without the protection of OAuth2.0

Bellow line checks OAuth token only if authorization header is present
https://github.com/kumuluz/kumuluzee-jwt-auth/blob/7f6255312188e8c4cf12a93414a4df2596b5c62a/src/main/java/com/kumuluz/ee/jwt/auth/filter/JWTAuthorizationFilter.java#L76

The suggested fix for this security issue is to remove that header check, or to reject such request if authorization header is not present.

**Comment by osbeorn** [comment]
You are correct. The issue is now fixed by denying access if authorization header is not present or the bearer token is not in the authorization header.
