### ISSUE TITLE
How to get the token into the application?

### ISSUE THREAD

**Issue by OhMyDeera** [kumuluz/kumuluzee-jwt-auth#2]
Once you've added the filters for the JAX-RS Application:

    @ApplicationPath("v1")
    public class CustomerApplication extends Application {

        @Override
        public Set<Class<?>> getClasses() {

            Set<Class<?>> classes = new HashSet<>();

            // microprofile jwt auth filters
            classes.add(JWTAuthorizationFilter.class);
            classes.add(JWTRolesAllowedDynamicFeature.class);

            // resources
            classes.add(CustomerResource.class);

            return classes;
        }

    }

and added in the configuration:

    kumuluzee:
      jwt-auth:
        public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnOTgnGBISzm3pKuG8QXMVm6eEuTZx8Wqc8D9gy7vArzyE5QC/bVJNFwlz...
        issuer: http://example.org/auth

How do you actually get the token INTO this application? do you pass it in the header of the request? i.e:
-H "Authorization: Bearer <TOKEN_HERE>" 

What i want to know is what dependencies are required, and how do i get the token in so that i can use 
        @Inject JsonWebToken principal 
so that it will actually have the token?

EDIT: 
Also with regards to the "@Inject JsonWebToken principal " what class is that meant to be put in?

**Comment by jmezna** [comment]
Yes, you pass the token with the Authorization header: -H "Authorization: Bearer <TOKEN_HERE>"

Token is then typically injected into the JAX-RS resource. Have a look at this sample https://github.com/kumuluz/kumuluzee-samples/blob/master/kumuluzee-microProfile-1.2/

**Comment by OhMyDeera** [comment]
The issue i get with that is the following:
org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=JsonWebToken,parent=OMResource,qualifiers={},position=-1,optional=false,self=false,unqualified=null,945047158)

So how do i ensure that the JWT is available for injection??

**Comment by jmezna** [comment]
Did you include the kumuluzee-cdi-weld dependency and the beans.xml resource file?

**Comment by OhMyDeera** [comment]
I have the kumuluzee-cdi-weld dependency and i just added in the beans now, it looks like this:
`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_2_0.xsd"
       bean-discovery-mode="all" version="2.0">
</beans>`

So i believe it is getting injected now, but the principal is null.

Am i missing anything else?

**Comment by jmezna** [comment]
From the information you provided It does not look like you are missing anything. Are you providing a token properly? Try comparing your project with the working sample https://github.com/kumuluz/kumuluzee-samples/blob/master/kumuluzee-microProfile-1.2/

**Comment by OhMyDeera** [comment]
Its identical, Is there anything i need to include in my web.xml?
Also, are the roles in the JWT internally checked against the @RolesAllowed on an endpoint, or do i have to manually create a SecurityContext?

**Comment by OhMyDeera** [comment]
Also, i ran the microprofile-1.2 project and tested to see if that would work. I passed a JWT token in through the header and changed the config to use my public key and issuer name and got this response:
2018-06-29 10:48:15.658 INFO -- com.kumuluz.ee.health.HealthInitiator -- Initializing Health extension
2018-06-29 10:48:15.659 INFO -- com.kumuluz.ee.health.HealthInitiator -- Registering health servlet on /health
2018-06-29 10:48:15.660 INFO -- com.kumuluz.ee.health.HealthInitiator -- Starting health logger to log health check results every 60 s
2018-06-29 10:48:15.751 INFO -- com.kumuluz.ee.metrics.MetricsInitiator -- Initialising KumuluzEE Metrics
2018-06-29 10:48:15.762 INFO -- com.kumuluz.ee.metrics.MetricsInitiator -- Registering metrics servlet on /metrics/*
2018-06-29 10:48:15.764 INFO -- com.kumuluz.ee.metrics.MetricsInitiator -- Registering metrics filter customersEndpoint on /v1/customers/* with status codes [200, 201, 204, 400, 404, 500]
2018-06-29 10:48:15.778 INFO -- org.eclipse.jetty.server.session.DefaultSessionIdManager -- DefaultSessionIdManager workerName=node0
2018-06-29 10:48:15.778 INFO -- org.eclipse.jetty.server.session.DefaultSessionIdManager -- No SessionScavenger set, using defaults
2018-06-29 10:48:15.779 INFO -- org.eclipse.jetty.server.session.HouseKeeper -- Scavenging every 660000ms
2018-06-29 10:48:16.160 INFO -- org.eclipse.jetty.server.handler.ContextHandler -- Started o.e.j.w.WebAppContext@3b2da18f{/,jar:file:/home/omar/dev/code/kumuluzee-microProfile-1.2/target/kumuluzee-microProfile-1.2-3.0.0-SNAPSHOT.jar!/webapp,AVAILABLE}
2018-06-29 10:48:16.229 INFO -- org.eclipse.jetty.server.AbstractConnector -- Started ServerConnector@472698d{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2018-06-29 10:48:16.229 INFO -- org.eclipse.jetty.server.Server -- Started @3280ms
2018-06-29 10:48:16.229 INFO -- com.kumuluz.ee.EeApplication -- KumuluzEE started successfully
PRINCIPAL: null


So i don't know why this is happening now if the example isn't working either
Maybe there is some configuration that needs to be done to make it work?

**Comment by jmezna** [comment]
Try:

  jwt-auth:
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA33TqqLR3eeUmDtHS89qF
                  3p4MP7Wfqt2Zjj3lZjLjjCGDvwr9cJNlNDiuKboODgUiT4ZdPWbOiMAfDcDzlOxA
                  04DDnEFGAf+kDQiNSe2ZtqC7bnIc8+KSG/qOGQIVaay4Ucr6ovDkykO5Hxn7OU7s
                  Jp9TP9H0JH8zMQA6YzijYH9LsupTerrY3U6zyihVEDXXOv08vBHk50BMFJbE9iwF
                  wnxCsU5+UZUZYw87Uu0n4LPFS9BT8tUIvAfnRXIEWCha3KbFWmdZQZlyrFw0buUE
                  f0YN3/Q0auBkdbDR/ES2PbgKTJdkjc/rEeM0TxvOUf7HuUNOhrtAVEN1D5uuxE1W
                  SwIDAQAB
      issuer: https://jwt-idp.example.com

Token:

eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2p3dC1pZHAuZXhhbXBsZS5jb20iLCJzdWIiOiJtYWlsdG86bWlrZUBleGFtcGxlLmNvbSIsIm5iZiI6MTUzMDI2Njg1MCwiZXhwIjoxNTMwMjcwNDUwLCJpYXQiOjE1MzAyNjY4NTAsImp0aSI6ImlkMTIzNDU2IiwidHlwIjoiaHR0cHM6Ly9leGFtcGxlLmNvbS9yZWdpc3RlciJ9.r72Y7805-TIDF3vacckwhxDgyFh6rj1P82aw1L_9AcjI0kXUHk7QNW4JgM9XFl3IffOAiYBPOtP0L-zO-4caX3MA3LBbrOPXTXychXFdCZh0cb5U7RCETM5RMVqj5OIZdvm4c7qwMBC-PrTaUTJROt_VVnOF9Kgpf6BXvR0_FnHXdo7B2yysYkkZ8lJ550vQOYm1vIgQcNX3bIVsyyVDL6hmoXhB5MFU6keP4dmvygXjGTAf2ua1i5_3Y1WehTF4pb49kLFxT8EHIzsE46eNL-0qpozXf8yMS7EPTNRtCG_G6sKymWssmVkU2YvJP67fodXM9HX-Q5aZEkGvp-FGSw


I generated the token on http://kjur.github.io/jsjws/tool_jwt.html, using the PKCS #8

**Comment by OhMyDeera** [comment]
I tried it with those and it works now, i think it was due to some missing fields in the payload of my token:
-nbf
-jti
-typ

Are those required for a JWT to be valid? would that be causing the null JsonWebToken?
If that's the case, maybe you should explicitly say which fields are required.

**Comment by OhMyDeera** [comment]
The source code in claims:
// The base set of required claims that MUST have non-null values in the JsonWebToken
iss("Issuer", String.class),
sub("Subject", String.class),
exp("Expiration Time", Long.class),
iat("Issued At Time", Long.class),
jti("JWT ID", String.class),
upn("MP-JWT specific unique principal name", String.class),
groups("MP-JWT specific groups permission grant", Set.class),
raw_token("MP-JWT specific original bearer token", String.class),

Though the token that you provided didn't have a groups tag yet it still worked.

**Comment by jmezna** [comment]
Token have to be compliant with the MicroProfile JWT Auth specification, which can be found here https://github.com/eclipse/microprofile-jwt-auth/releases/download/1.1/microprofile-jwt-auth-spec-1.1.pdf

**Comment by OhMyDeera** [comment]
Thank you very much!
