### ISSUE TITLE
How to map roles?

### ISSUE THREAD

**Issue by aks1892** [kumuluz/kumuluzee-jwt-auth#3]
We have JWT working correctly and can use the @RolesAllowed tag successfully if we give it a legitimate AD role name (e.g. ThisIsMyApplicationWriteRole). How can this be mapped to a different name? I tried adding the following in the yaml config...

  security:
    roles:
      appWrite: ThisIsMyApplicationWriteRole

...and then using "appWrite" in @RolesAllowed but that did not work.

**Comment by osbeorn** [comment]
Custom role mapping is not supported by the MP JWT-AUTH 1.0 specification - only roles that are present in the groups claim are considered when using the @RolesAllowed annotation.

**Comment by aks1892** [comment]
Will this be available in the next version? If so, when is the next version due?

**Comment by osbeorn** [comment]
It would seem that role mapping is currently not being considered for any new MP JWT-AUTH version in the nearby future.
