### ISSUE TITLE
Contribute but repo doesn't build

### ISSUE THREAD

**Issue by danpfe** [kumuluz/kumuluzee-jwt-auth#4]
Hi guys,

I forked your repo at https://github.com/kumuluz/kumuluzee-jwt-auth/compare/master...danpfe:master because I wanted to contribute JWKS-support for the MP-JWT-feature.

Unfortunately right from the outset I was met by a couple of issues and I wanted to ask if you guys want fixes in a PR besides what the PR was meant for initially.

1. The project doesn't build using regular public repositories (there is code using bouncycastle but there is no such dependency, there is also a dependency on snapshot-versions of kumuluzee-components which aren't available either).
2. 90 tests fail using Java 1.8.0_181 and Maven 3.5.4 (although I must add that I replaced the bouncycastle-Base64-code with Java 8's Base64-class and resorted to setting non-SNAPSHOT-versions in the POM-dependency).

Naturally the more troubling issue are the failed tests. I would like to be able to run the entire test suite and perhaps some tests of my own before I create the PR so I would like to ask how your setup looks like (some special version of Java or Maven or KumuluzEE required) and as I mentioned before if it is ok with you guys that a couple of unrelated changes go into the PR?

Also like to add that I tried to build it without tests and used the kumuluzee-jwt-auth-feature in my project and there everything seems to work, so I don't think the production code itself is really broken.

Thanks!

**Comment by urbim** [comment]
Hi, thanks for your interest!

I looked at your project. All of your problems are related to the java-jwt library, which you updated from 3.2.0 to 3.4.0.

The bouncycastle dependency came from the java-jwt library but was removed somewhere between 3.2.0 and 3.4.0. I don't think there is a particular reason for using bouncycastle dependency over Java 8 library, so I think this change is ok.

The updated java-jwt library also introduces a new library jackson-databind 2.9.6, which conflicts with the version we use in the kumuluzee-jax-rs-jersey (2.8.10). This library must be excluded from the java-jwt library and reincluded in the base pom with the correct version.

With the attached patch applied to your project, all tests run fine.

[0001-Fixed-jackson-conflict-and-updated-tests.patch.txt](https://github.com/kumuluz/kumuluzee-jwt-auth/files/2373917/0001-Fixed-jackson-conflict-and-updated-tests.patch.txt)

As for the SNAPSHOT versions, we tend to keep versions in snapshots during development and change them to release versions before we perform a release. In your case I think it's fine if you use kumuluz version 2.5.3 and kumuluz arquillian container version 1.0.0 during development but leave versions as they are in the final PR.

**Comment by MBJuric** [comment]
Hi Daniel,
It would be great if you could contribute JWKS-support for the MP-JWT-feature. Much appreciated.
Thanks!

**Comment by danpfe** [comment]
Hi @urbim, interesting you mentioned that dependency because I wasn't able to build without test errors directly after check-out. I simply (although admittedly without any particular reason) updated it at a later point when I was anyway fiddling around with the POM.

In any case, I will apply your patch and see how it goes. Will report back in a while.

**Comment by danpfe** [comment]
@urbim Seeing still a lot of errors (although only 84 now). Now I am guessing wildly but is it possible you run this against some repo where some deps could be slightly different?

I will dig more in the test errors now using kumuluzee 2.5.3 and kumuluzee-arquillian 1.0.0.

**Comment by urbim** [comment]
Since you couldn't build the project even directly after check-out and our Travis build completes fine I'm guessing the problem is at your side.

Are you running tests with `mvn clean test`? What OS and JDK are you using? Can you provide the output log of `mvn clean test` command?

**Comment by danpfe** [comment]
Hi urbim, guess it's possible. Following gist is after checkout (althought changed to kumuluzee 2.5.3 and arquillian 1.0.0 because I am missing SNAPSHOT-versions): https://gist.github.com/danpfe/21e4ac98547bfdedb850ab8cc3d92c82#file-build-directly-from-source

This gist is from the forked repo: https://gist.github.com/danpfe/0e0eabd04ac58ea9bb2995d5e00dbc3d#file-build-from-forked-repo

OS: macOS High Sierra 10.13.6
Java: OpenJDK 64-Bit Server VM (Zulu 8.31.0.1-macosx) (build 25.181-b02, mixed mode)
Maven: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)

settings.xml only contains a couple of server passwords, no mirror. Also tried to add jackson-databind as suggested, no joy.

Any idea is greatly appreciated :)

**Comment by urbim** [comment]
@danpfe I tried reproducing the error but my builds always complete fine. I tried on Linux, Windows and Mac machine with the exact same configuration as yours (changed kumuluzee and arquillian adapter versions from master branch).

The reports you sent indicate that the server under test always returns 404. Are you running any other server on localhost:8080? (Docker containers, daemons etc.) You can try debugging the test and checking if the received response is really from the KumuluzEE server (there should be KumuluzEE header).

Alternatively, can you try running the tests on some other machine?

**Comment by danpfe** [comment]
Don't think so but will recheck. If that's the case and I missed it I will probably have to wallow in a pool of shame the rest of the day ;-)

**Comment by danpfe** [comment]
Duh, you were right. There was a half dead process still running in the background occupying that port. Jeeze :) Once again it's proven that assumptions are the mother of all f* ups, as I thought that "if it doesn't build from start there is probably something wrong with the latest commit" and didn't look at much else.

In any case, now the tests are going through so I'll close this issue and finish off the PR instead.
