### ISSUE TITLE
Official release including JWKS-feature

### ISSUE THREAD

**Issue by danpfe** [kumuluz/kumuluzee-jwt-auth#6]
Hi guys (and specifically @urbim and @MBJuric), now that the JWKS-feature I contributed was merged and some changes from @urbim been in the repo for a while (which I have been running for a couple of weeks in prod without noticable issues), I am starting to be curious when the next release of this component is scheduled?

Thanks!

**Comment by MBJuric** [comment]
Hi. Thanks again for your contribution. We will release the component in the beginning of next week.

**Comment by danpfe** [comment]
@MBJuric Great to hear, thanks!
