### ISSUE TITLE
Adding Filter & Dynamic Feature classes to application getClasses

### ISSUE THREAD

**Issue by aks1892** [kumuluz/kumuluzee-jwt-auth#7]
The documentation states to override getClasses and add JWT Filter and Dynamic Feature classes. This disables resource scanning so other resources have to be manually added. Can the Filter and Dynamic Feature classes be added via getProperties instead?

**Comment by danpfe** [comment]
@aks1892 I did it by simply adding two empty classes to my project. One extends JWTRolesAllowedDynamicFeature (and annotating it @Provider @Priority(2000)) and another extends JWTAuthorizationFilter (annotating it with @Provider @Priority(1000) @PreMatching).

**Comment by aks1892** [comment]
Thanks! That worked.
